//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmail {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("crmail.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug(s).
        /// </summary>
        internal static string EmailBugs {
            get {
                return ResourceManager.GetString("EmailBugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string EmailDescription {
            get {
                return ResourceManager.GetString("EmailDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewers.
        /// </summary>
        internal static string EmailReviewer {
            get {
                return ResourceManager.GetString("EmailReviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;gt;Domain Expert&amp;lt;.
        /// </summary>
        internal static string EmailReviewerNotPresent {
            get {
                return ResourceManager.GetString("EmailReviewerNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contents of the application config file is not correct. Please check crmail.exe.config.
        /// </summary>
        internal static string ErrBadConfigFile {
            get {
                return ResourceManager.GetString("ErrBadConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed: {0}.
        /// </summary>
        internal static string ErrFail {
            get {
                return ResourceManager.GetString("ErrFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find shelveset {0}.
        /// </summary>
        internal static string ErrFailToGetShelveset {
            get {
                return ResourceManager.GetString("ErrFailToGetShelveset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string InfoConnected {
            get {
                return ResourceManager.GetString("InfoConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0} ....
        /// </summary>
        internal static string InfoConnecting {
            get {
                return ResourceManager.GetString("InfoConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating e-mail....
        /// </summary>
        internal static string InfoGeneratingEmail {
            get {
                return ResourceManager.GetString("InfoGeneratingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting shelveset....
        /// </summary>
        internal static string InfoGettingShelveset {
            get {
                return ResourceManager.GetString("InfoGettingShelveset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelveset {0} retrieved.
        /// </summary>
        internal static string InfoGotShelveset {
            get {
                return ResourceManager.GetString("InfoGotShelveset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates an email for code review from a shelveset..
        /// </summary>
        internal static string InfoHelpDescription {
            get {
                return ResourceManager.GetString("InfoHelpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Sample: {0}.
        /// </summary>
        internal static string InfoHelpSample {
            get {
                return ResourceManager.GetString("InfoHelpSample", resourceCulture);
            }
        }
    }
}
